spring:
  application:
    name: ms-recommendation
  config:
    import: "classpath:application-openapi.yml"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    '[bo.edu.ucb.microservices]': DEBUG
    '[org.springframework.data.mongodb.core.MongoTemplate]': DEBUG
    
---
spring.config.activate.on-profile: docker
server.port: 8080
spring.data.mongodb.host: mongodb