version: '2.1'

services:
  product:
    image: product-service:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  product-p1:
    image: product-service:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  recommendation:
    image: recommendation-service:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  recommendation-p1:
    image: recommendation-service:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  review:
    image: review-service:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  review-p1:
    image: review-service:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  product-composite:
    image: product-composite-service:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,kafka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    extra_hosts:
      - "keycloak.ucb.edu.bo:host-gateway"
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started

  mongodb:
    image: mongo:8
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 60

  postgresql:
    image: postgres:16-alpine
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=review-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d review-db'"]
      interval: 5s
      timeout: 2s
      retries: 60

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    restart: always
    mem_limit: 1024m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    restart: always
    mem_limit: 512m
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  eureka:
    image: eureka-server:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-server:
        condition: service_healthy

  gateway:
    image: gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SERVER_SSL_KEY_STORE=file:/keystore/edge-test.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    extra_hosts:
      - "keycloak.ucb.edu.bo:host-gateway"
    volumes:
      - ${KEYSTORE_PATH:-./keystore}:/keystore
    mem_limit: 512m
    ports:
      - "8443:8443"
    depends_on:
      config-server:
        condition: service_healthy

  config-server:
    image: config:latest
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl -f -u ${CONFIG_SERVER_USR}:${CONFIG_SERVER_PWD} http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5