springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: bo.edu.ucb.microservices.core.msreview.controller
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: API Review
    description: Servicio de información de reseñas de productos
    termsOfService: https://www.miempresa.com/terminos
    license: Licencia MIT
    licenseUrl: https://opensource.org/licenses/MIT
    externalDocDesc: Documentación en Wiki
    externalDocUrl: https://www.miempresa.com/wiki
    contact:
      name: Soporte Mi Empresa
      url: https://www.miempresa.com/contacto
      email: soporte@miempresa.com

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, Formato inválido de la solicitud. Ver mensaje de respuesta para más información.
    notFound.description: Not found, el id especificado no existe.
    unprocessableEntity.description: Unprocessable entity, no se puede procesar los parametros de entrada. Ver mensaje de respuesta para más información.

  review:
    get-review:
      description: Retorna las reseñas de un producto en base al id de producto proporcionado.
      notes: |
        # Respuesta exitosa
        Si el id del producto solicitado es encontrado el método retornará las reseñas del producto.
        Si no se encuentran reseñas para un producto, se retorna una lista vacia.

        # Respuestas con error 
        1. Si el id del producto es inválido se devuelve un error **422 - Unprocessable Entity**
      parameters:
        productId: ID del producto para el cual se buscarán reseñas